const carList = [
    {
        brand: "BYD",
        model: "Dolphin",
        price: 11000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "BYD",
        model: "Dolphin Performance",
        price: 11500000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "BYD",
        model: "Atto 3",
        price: 15000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "BYD",
        model: "Atto 3 Performance",
        price: 17000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "BYD",
        model: "Seal",
        price: 21000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "BYD",
        model: "Sealion",
        price: 22000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "Sonet",
        price: 7000000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "Stonic",
        price: 9000000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "EV3",
        price: 13000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "Seltos",
        price: 14000000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "EV5 Electric",
        price: 16000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "Sportage HEV/PHEV",
        price: 19000000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "EV6 Electric",
        price: 19000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "Sorento HEV/PHEV",
        price: 22000000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "Carnival HEV/PHEV",
        price: 23000000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Kia",
        model: "EV9 Electric",
        price: 27000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "Attrage",
        price: 8890000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "Xpander",
        price: 12190000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "Xforce/Outlander",
        price: 14890000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "Xforce/Outlander",
        price: 18000000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "Xpander Cross",
        price: 14590000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "Eclipse Cross",
        price: 0, // TBD
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "L200 Pickup Truck",
        price: 0, // TBD
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Mitsubishi",
        model: "Montero Sport",
        price: 44890000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Wigo",
        price: 6700000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Raize",
        price: 9500000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Hilux (Single Cab)",
        price: 10600000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Rush",
        price: 15300000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Ativ",
        price: 15500000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Hilux (Double Cab)",
        price: 15800000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Hiace",
        price: 14900000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Coaster",
        price: 16900000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Yaris Cross",
        price: 17500000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Corolla",
        price: 22900000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Prius",
        price: 23000000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Corolla Cross",
        price: 28200000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "RAV4",
        price: 30500000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Camry",
        price: 35000000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Land Cruiser 79",
        price: 21300000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Fortuner",
        price: 49000000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Alphard",
        price: 57000000,
        type: "Hybrid",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Land Cruiser 250",
        price: 61500000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Toyota",
        model: "Land Cruiser 300",
        price: 94000000,
        type: "Diesel",
        capacity: "",
    },
    {
        brand: "Hyundai",
        model: "Kona",
        price: 18000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "Hyundai",
        model: "Ionic 5",
        price: 22000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "Hyundai",
        model: "Ionic 6",
        price: 16000000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "DFSK",
        model: "Series 3 (premium)",
        price: 12500000,
        type: "EV",
        capacity: "",
    },
    {
        brand: "DFSK",
        model: "Glory i auto",
        price: 16500000,
        type: "Petrol",
        capacity: "",
    },
    {
        brand: "Beigin",
        model: "Premium",
        price: 16000000,
        type: "Petrol",
        capacity: "",
    },
];

export const groupedCars = () => {
    return carList.reduce((acc, car) => {
        if (!acc[car.brand]) {
            acc[car.brand] = [];
        }
        acc[car.brand].push(car);
        return acc;
    }, {} as Record<string, typeof carList>);
};
